# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Rubaiat Hossain
paginate:       5
baseurl:        ""
url:            "https://rshopnil.github.io"


# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Rubaiat Hossain
  url:          http://rshopnil.github.io
  email:        shopnil.lancer@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
